name = "PyFortran90Namelists"
uuid = "e44308e6-bd5b-11e9-2850-49daf8f1ec40"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
CondaPkg = "0.2"
VersionParsing = "1.1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
